### ISSUE TITLE
Spectators & Dead players can +use the vehicle, & Ducking perspective issue

### ISSUE THREAD

**Issue by matsys-regressiontest** [ficool2/vscript_vehicle#1]
---
![spec_kill](https://github.com/ficool2/vscript_vehicle/assets/114315187/ab48cee2-5010-4d5f-960f-02f353f2093f)
![dead_kill](https://github.com/ficool2/vscript_vehicle/assets/114315187/167e512e-21c9-49cd-bac1-9fbbffc83dbf)
Spectators and Dead players can both +use the vehicle and control it.
+use again makes them no longer control the vehicle.

---
---
![respawn](https://github.com/ficool2/vscript_vehicle/assets/114315187/aa51e37b-3b8b-4c70-b924-44d4d3d4ba94)
If the player is still controlling the vehicle once the respawn timer hits zero, they are respawned (or ejected) next to the vehicle rather than at a spawn point, and they are A-posing until they switch weapons.
If they are no longer controlling the vehicle on respawn, then they are spawned normally at a spawn point.

---
---
![duck_before](https://github.com/ficool2/vscript_vehicle/assets/114315187/25366fe1-24d5-4918-b736-87e20ae8e2fe)
![duck_after](https://github.com/ficool2/vscript_vehicle/assets/114315187/a73932b7-820e-46c4-8e64-568fcda33341)
Also, +duck while in the vehicle breaks your perspective by lowering it until you exit and reenter the vehicle.
-duck does not fix your perspective.

---

**Comment by ficool2** [comment]
Fixed in latest version
